 
INSERT INTO PRODUCT_DETAILS VALUES(1,'fan',300);
INSERT INTO PRODUCT_DETAILS VALUES(2,'ac',300);
 
INSERT INTO ORDER_DETAILS VALUES(1,'raju','2019-06-06','anna salai plotno 67 chennai',1234);



INSERT INTO ORDER_PRODUCT_DETAILS VALUES(1,1);
INSERT INTO ORDER_PRODUCT_DETAILS VALUES(2,1);





